---
title: "Proyect"
author: "Esteban Ladino Fajardo"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
  pdf_document: default
bibliography:
- ref/pacUse.bib
- ref/main.bib
editor_options: 
  markdown: 
    wrap: 72
---



```{r, label = "setup", echo = FALSE, results= 'hide', message = FALSE, warning = FALSE}
knitr::opts_chunk$set(fig.show = 'as.is', fig.height = 4, fig.align = "center", fig.width = 4, prompt = FALSE, highlight = TRUE, tidy = FALSE, warning = FALSE, message = FALSE, echo = TRUE, tidy.opts=list(blank = TRUE, width.cutoff= 65))
# Lists of R packages used
# PackagesUsed <- c("readr","dplyr","PASWR2","DT","DataExplorer","tidyverse")
PackagesUsed <- c("markovchain")
# Install packages
# install.packages(PackagesUsed)
# Write bib information
knitr::write_bib(PackagesUsed, file = "./ref/pacUse.bib")
# Load packages
lapply(PackagesUsed, library, character.only = TRUE)
```

De acuerdo con @spedicatoAnswerCalculateTransition2013 y con la ayuda de @PhindAISearch se obtiene la matriz de transición.

```{r}
sequence <- c("a", "b", "a", "a", "a", "a", "b", "a", "b", "a", 
              "b", "a", "a", "b", "b", "b", "a")
mcFit <- markovchain::markovchainFit(data=sequence)
transition_matrix <- mcFit$estimate@transitionMatrix
print(transition_matrix)
```


```{r}

```


## Referencias